name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 24.x]

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - name: Test
      run: bun test.js